version: '3.9'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: react-vite-nginx
    container_name: react-vite-nginx
    ports:
      - "8080:80"
    restart: unless-stopped
